# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f995a9a508402286e49bb6b44236dcbae4749d6bc19bad8347b07fc418289fad5efe861a8e64948536c6ed16f18e2a0378c14ed7c2e4767668ed74b539358a57

test:
  secret_key_base: 2366c69af168c111aed9753b28d110cb639b1b539aa7dc95864c4b9cf44ac0f067ab40bb5a9d12c28a3d8997347ea692bddd9bbd0675c8bcfcafdd5dc3a7de52

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
